apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: teranode-operator-sr-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: teranode-operator-sr-role
subjects:
- kind: ServiceAccount
  name: teranode-operator-service-runner
  namespace: teranode-operator-system
