# permissions for end users to edit assets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: asset-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: teranode-operator
    app.kubernetes.io/part-of: teranode-operator
    app.kubernetes.io/managed-by: kustomize
  name: asset-editor-role
rules:
  - apiGroups:
      - teranode.bsvblockchain.org
    resources:
      - assets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - teranode.bsvblockchain.org
    resources:
      - assets/status
    verbs:
      - get
