# permissions for end users to view legacies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: legacy-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: teranode-operator
    app.kubernetes.io/part-of: teranode-operator
    app.kubernetes.io/managed-by: kustomize
  name: legacy-viewer-role
rules:
- apiGroups:
  - teranode.bsvblockchain.org
  resources:
  - legacies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - teranode.bsvblockchain.org
  resources:
  - legacies/status
  verbs:
  - get
