---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - persistentvolumeclaims
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - teranode.bsvblockchain.org
  resources:
  - assets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - teranode.bsvblockchain.org
  resources:
  - assets/finalizers
  verbs:
  - update
- apiGroups:
  - teranode.bsvblockchain.org
  resources:
  - assets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - teranode.bsvblockchain.org
  resources:
  - blockassemblies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - teranode.bsvblockchain.org
  resources:
  - blockassemblies/finalizers
  verbs:
  - update
- apiGroups:
  - teranode.bsvblockchain.org
  resources:
  - blockassemblies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - teranode.bsvblockchain.org
  resources:
  - blockchains
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - teranode.bsvblockchain.org
  resources:
  - blockchains/finalizers
  verbs:
  - update
- apiGroups:
  - teranode.bsvblockchain.org
  resources:
  - blockchains/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - teranode.bsvblockchain.org
  resources:
  - blockpersisters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - teranode.bsvblockchain.org
  resources:
  - blockpersisters/finalizers
  verbs:
  - update
- apiGroups:
  - teranode.bsvblockchain.org
  resources:
  - blockpersisters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - teranode.bsvblockchain.org
  resources:
  - bootstraps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - teranode.bsvblockchain.org
  resources:
  - bootstraps/finalizers
  verbs:
  - update
- apiGroups:
  - teranode.bsvblockchain.org
  resources:
  - bootstraps/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - teranode.bsvblockchain.org
  resources:
  - coinbases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - teranode.bsvblockchain.org
  resources:
  - coinbases/finalizers
  verbs:
  - update
- apiGroups:
  - teranode.bsvblockchain.org
  resources:
  - coinbases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - teranode.bsvblockchain.org
  resources:
  - faucets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - teranode.bsvblockchain.org
  resources:
  - faucets/finalizers
  verbs:
  - update
- apiGroups:
  - teranode.bsvblockchain.org
  resources:
  - faucets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - teranode.bsvblockchain.org
  resources:
  - miners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - teranode.bsvblockchain.org
  resources:
  - miners/finalizers
  verbs:
  - update
- apiGroups:
  - teranode.bsvblockchain.org
  resources:
  - miners/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - teranode.bsvblockchain.org
  resources:
  - nodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - teranode.bsvblockchain.org
  resources:
  - nodes/finalizers
  verbs:
  - update
- apiGroups:
  - teranode.bsvblockchain.org
  resources:
  - nodes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - teranode.bsvblockchain.org
  resources:
  - peers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - teranode.bsvblockchain.org
  resources:
  - peers/finalizers
  verbs:
  - update
- apiGroups:
  - teranode.bsvblockchain.org
  resources:
  - peers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - teranode.bsvblockchain.org
  resources:
  - propagations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - teranode.bsvblockchain.org
  resources:
  - propagations/finalizers
  verbs:
  - update
- apiGroups:
  - teranode.bsvblockchain.org
  resources:
  - propagations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - teranode.bsvblockchain.org
  resources:
  - subtreevalidators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - teranode.bsvblockchain.org
  resources:
  - subtreevalidators/finalizers
  verbs:
  - update
- apiGroups:
  - teranode.bsvblockchain.org
  resources:
  - subtreevalidators/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - teranode.bsvblockchain.org
  resources:
  - validators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - teranode.bsvblockchain.org
  resources:
  - validators/finalizers
  verbs:
  - update
- apiGroups:
  - teranode.bsvblockchain.org
  resources:
  - validators/status
  verbs:
  - get
  - patch
  - update
