---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - teranode.bsvblockchain.org
  resources:
  - assets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - teranode.bsvblockchain.org
  resources:
  - assets/finalizers
  verbs:
  - update
- apiGroups:
  - teranode.bsvblockchain.org
  resources:
  - assets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - teranode.bsvblockchain.org
  resources:
  - blockchains
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - teranode.bsvblockchain.org
  resources:
  - blockchains/finalizers
  verbs:
  - update
- apiGroups:
  - teranode.bsvblockchain.org
  resources:
  - blockchains/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - teranode.bsvblockchain.org
  resources:
  - blockpersisters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - teranode.bsvblockchain.org
  resources:
  - blockpersisters/finalizers
  verbs:
  - update
- apiGroups:
  - teranode.bsvblockchain.org
  resources:
  - blockpersisters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - teranode.bsvblockchain.org
  resources:
  - faucets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - teranode.bsvblockchain.org
  resources:
  - faucets/finalizers
  verbs:
  - update
- apiGroups:
  - teranode.bsvblockchain.org
  resources:
  - faucets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - teranode.bsvblockchain.org
  resources:
  - nodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - teranode.bsvblockchain.org
  resources:
  - nodes/finalizers
  verbs:
  - update
- apiGroups:
  - teranode.bsvblockchain.org
  resources:
  - nodes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - teranode.bsvblockchain.org
  resources:
  - peers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - teranode.bsvblockchain.org
  resources:
  - peers/finalizers
  verbs:
  - update
- apiGroups:
  - teranode.bsvblockchain.org
  resources:
  - peers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - teranode.bsvblockchain.org
  resources:
  - propagations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - teranode.bsvblockchain.org
  resources:
  - propagations/finalizers
  verbs:
  - update
- apiGroups:
  - teranode.bsvblockchain.org
  resources:
  - propagations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - teranode.bsvblockchain.org
  resources:
  - subtreevalidators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - teranode.bsvblockchain.org
  resources:
  - subtreevalidators/finalizers
  verbs:
  - update
- apiGroups:
  - teranode.bsvblockchain.org
  resources:
  - subtreevalidators/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - teranode.bsvblockchain.org
  resources:
  - transactionblasters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - teranode.bsvblockchain.org
  resources:
  - transactionblasters/finalizers
  verbs:
  - update
- apiGroups:
  - teranode.bsvblockchain.org
  resources:
  - transactionblasters/status
  verbs:
  - get
  - patch
  - update
