# permissions for end users to view subtreevalidators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: subtreevalidator-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: teranode-operator
    app.kubernetes.io/part-of: teranode-operator
    app.kubernetes.io/managed-by: kustomize
  name: subtreevalidator-viewer-role
rules:
  - apiGroups:
      - teranode.bsvblockchain.org
    resources:
      - subtreevalidators
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - teranode.bsvblockchain.org
    resources:
      - subtreevalidators/status
    verbs:
      - get
