# permissions for end users to view utxopersisters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: teranode-operator
    app.kubernetes.io/managed-by: kustomize
  name: utxopersister-viewer-role
rules:
  - apiGroups:
      - teranode.bsvblockchain.org
    resources:
      - utxopersisters
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - teranode.bsvblockchain.org
    resources:
      - utxopersisters/status
    verbs:
      - get
