apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: teranode-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
      - description: Miner is the Schema for the miners API
        displayName: Miner
        kind: Miner
        name: miners.teranode.bsvblockchain.org
        version: v1alpha1
      - description: AlertSystem is the Schema for the alertsystems API
        displayName: Alert System
        kind: AlertSystem
        name: alertsystems.teranode.bsvblockchain.org
        version: v1alpha1
      - description: Asset is the Schema for the assets API
        displayName: Asset
        kind: Asset
        name: assets.teranode.bsvblockchain.org
        version: v1alpha1
      - description: BlockAssembly is the Schema for the blockassemblies API
        displayName: Block Assembly
        kind: BlockAssembly
        name: blockassemblies.teranode.bsvblockchain.org
        version: v1alpha1
      - description: Blockchain is the Schema for the blockchains API
        displayName: Blockchain
        kind: Blockchain
        name: blockchains.teranode.bsvblockchain.org
        version: v1alpha1
      - description: BlockPersister is the Schema for the blockpersisters API
        displayName: Block Persister
        kind: BlockPersister
        name: blockpersisters.teranode.bsvblockchain.org
        version: v1alpha1
      - description: BlockValidator is the Schema for the blockvalidators API
        displayName: Block Validator
        kind: BlockValidator
        name: blockvalidators.teranode.bsvblockchain.org
        version: v1alpha1
      - description: Bootstrap is the Schema for the bootstraps API
        displayName: Bootstrap
        kind: Bootstrap
        name: bootstraps.teranode.bsvblockchain.org
        version: v1alpha1
      - description: Cluster is the Schema for the nodes API
        displayName: Cluster
        kind: Cluster
        name: clusters.teranode.bsvblockchain.org
        version: v1alpha1
      - description: Coinbase is the Schema for the coinbases API
        displayName: Coinbase
        kind: Coinbase
        name: coinbases.teranode.bsvblockchain.org
        version: v1alpha1
      - description: Faucet is the Schema for the faucets API
        displayName: Faucet
        kind: Faucet
        name: faucets.teranode.bsvblockchain.org
        version: v1alpha1
      - description: Legacy is the Schema for the legacies API
        displayName: Legacy
        kind: Legacy
        name: legacies.teranode.bsvblockchain.org
        version: v1alpha1
      - description: Peer is the Schema for the peers API
        displayName: Peer
        kind: Peer
        name: peers.teranode.bsvblockchain.org
        version: v1alpha1
      - description: Propagation is the Schema for the propagations API
        displayName: Propagation
        kind: Propagation
        name: propagations.teranode.bsvblockchain.org
        version: v1alpha1
      - description: RPC is the Schema for the rpcs API
        displayName: RPC
        kind: RPC
        name: rpcs.teranode.bsvblockchain.org
        version: v1alpha1
      - description: SubtreeValidator is the Schema for the subtreevalidators API
        displayName: Subtree Validator
        kind: SubtreeValidator
        name: subtreevalidators.teranode.bsvblockchain.org
        version: v1alpha1
      - description: UtxoPersister is the Schema for the utxopersisters API
        displayName: Utxo Persister
        kind: UtxoPersister
        name: utxopersisters.teranode.bsvblockchain.org
        version: v1alpha1
      - description: Validator is the Schema for the validators API
        displayName: Validator
        kind: Validator
        name: validators.teranode.bsvblockchain.org
        version: v1alpha1
  description: An operator that deploys the teranode services
  displayName: Teranode Operator
  icon:
    - base64data: ""
      mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
    - supported: true
      type: OwnNamespace
    - supported: false
      type: SingleNamespace
    - supported: false
      type: MultiNamespace
    - supported: false
      type: AllNamespaces
  keywords:
    - teranode
    - blockchain
    - bsv
  links:
    - name: Teranode Operator
      url: https://teranode-operator.domain
  maintainers:
    - email: dylan.murray@bsvblockchain.org
      name: Dylan Murray
  maturity: alpha
  provider:
    name: BSV Association
  version: 0.0.0
