apiVersion: teranode.bsvblockchain.org/v1alpha1
kind: Cluster
metadata:
  annotations:
  labels:
    app.kubernetes.io/created-by: teranode-operator
    app.kubernetes.io/instance: cluster
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cluster
    app.kubernetes.io/part-of: teranode-operator
    k8slens-edit-resource-version: v1alpha1
  name: sample-cluster
spec:
  alertSystem:
    enabled: true
    spec: {}
  asset:
    enabled: true
    spec:
      grpcIngress:
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: ast-grpc
        className: traefik-internal
        host: euw1-teranode-main-net-1-prod.ubsv.dev
      httpIngress:
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: web
        className: traefik-internal
        host: euw1-teranode-main-net-1-prod.ubsv.dev
      httpsIngress:
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
        className: traefik-internal
        host: euw1-teranode-main-net-1-prod.ubsv.dev
      deploymentOverrides:
        replicas: 1
        resources:
          requests:
            cpu: "0.5"
            memory: 500Mi
  blockAssembly:
    enabled: true
    spec: {}
  blockPersister:
    enabled: true
    spec: {}
  blockValidator:
    enabled: true
    spec: {}
  blockchain:
    enabled: true
    spec: {}
  bootstrap:
    enabled: false
    spec: {}
  coinbase:
    enabled: false
    spec:
      deploymentOverrides:
        replicas: 0
        resources:
          requests:
            cpu: 1
            memory: 1Gi
  configMapName: shared-config
  image: 434394763103.dkr.ecr.eu-north-1.amazonaws.com/ubsv:v2.2.116
  legacy:
    enabled: true
    spec: {}
  peer:
    enabled: true
    spec:
      grpcIngress:
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: peer-grpc
        className: traefik-internal
        host: euw1-teranode-main-net-1-prod.ubsv.dev
      deploymentOverrides:
        replicas: 1
        resources:
          requests:
            cpu: "0.5"
            memory: 500Mi
      wsIngress:
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: p2p-ws
        className: traefik-internal
        host: euw1-teranode-main-net-1-prod.ubsv.dev
      wssIngress:
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: p2p-wss
        className: traefik-internal
        host: euw1-teranode-main-net-1-prod.ubsv.dev
  propagation:
    enabled: true
    spec:
      grpcIngress:
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: prop-grpc
        className: traefik-internal
        host: euw1-teranode-main-net-1-prod.ubsv.dev
      deploymentOverrides:
        replicas: 1
        resources:
          requests:
            cpu: "0.5"
            memory: 500Mi
      serviceAnnotations:
        traefik.ingress.kubernetes.io/service.serversscheme: h2c
  rpc:
    enabled: true
    spec: {}
  subtreeValidator:
    enabled: true
    spec:
      deploymentOverrides:
        replicas: 1
        resources:
          requests:
            cpu: 1
            memory: 8Gi
      storageClass: fsx-lustre
      storageResources:
        requests:
          storage: 3600Gi
  utxoPersister:
    enabled: false
    spec: {}
  validator:
    enabled: false
    spec: {}
