apiVersion: teranode.bsvblockchain.org/v1alpha1
kind: Miner
metadata:
  labels:
    app.kubernetes.io/name: miner
    app.kubernetes.io/instance: miner-sample
    app.kubernetes.io/part-of: teranode-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: teranode-operator
  name: miner-sample
spec:
  # TODO(user): Add fields here
