apiVersion: teranode.bsvblockchain.org/v1alpha1
kind: Peer
metadata:
  labels:
    app.kubernetes.io/name: peer
    app.kubernetes.io/instance: peer-sample
    app.kubernetes.io/part-of: teranode-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: teranode-operator
  name: peer-sample
spec:
  # TODO(user): Add fields here
