apiVersion: teranode.bsvblockchain.org/v1alpha1
kind: Propagation
metadata:
  labels:
    app.kubernetes.io/name: propagation
    app.kubernetes.io/instance: propagation-sample
    app.kubernetes.io/part-of: teranode-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: teranode-operator
  name: propagation-sample
spec:
  resources:
    requests:
      cpu: 1
      memory: 1Gi
    limits:
      memory: 2Gi
  imagePullPolicy: Always
  replicas: 1
  deploymentOverrides:
    replicas: 1
    resources:
      requests:
        cpu: 1
        memory: 1Gi
      limits:
        memory: 2Gi
    imagePullPolicy: Always
