apiVersion: teranode.bsvblockchain.org/v1alpha1
kind: Legacy
metadata:
  labels:
    app.kubernetes.io/name: legacy
    app.kubernetes.io/instance: legacy-sample
    app.kubernetes.io/part-of: teranode-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: teranode-operator
  name: legacy-sample
spec:
# TODO(user): Add fields here
