apiVersion: teranode.bsvblockchain.org/v1alpha1
kind: UtxoPersister
metadata:
  labels:
    app.kubernetes.io/name: teranode-operator
    app.kubernetes.io/managed-by: kustomize
  name: utxopersister-sample
spec:
  resources:
    requests:
      cpu: 1
      memory: 1Gi
    limits:
      memory: 2Gi
  imagePullPolicy: Always
