apiVersion: teranode.bsvblockchain.org/v1alpha1
kind: Faucet
metadata:
  labels:
    app.kubernetes.io/name: faucet
    app.kubernetes.io/instance: faucet-sample
    app.kubernetes.io/part-of: teranode-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: teranode-operator
  name: faucet-sample
spec:
  # TODO(user): Add fields here
  resources:
    requests:
      cpu: 1
      memory: 1Gi
    limits:
      memory: 2Gi
  imagePullPolicy: Always
