apiVersion: teranode.bsvblockchain.org/v1alpha1
kind: BlockValidator
metadata:
  labels:
    app.kubernetes.io/name: blockvalidator
    app.kubernetes.io/instance: blockvalidator-sample
    app.kubernetes.io/part-of: teranode-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: teranode-operator
  name: blockvalidator-sample
spec:
# TODO(user): Add fields here
