apiVersion: teranode.bsvblockchain.org/v1alpha1
kind: Node
metadata:
  labels:
    app.kubernetes.io/name: node
    app.kubernetes.io/instance: node-sample
    app.kubernetes.io/part-of: teranode-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: teranode-operator
  name: node-sample
spec:
  startBlockchain: true
  startMiner: true

