apiVersion: teranode.bsvblockchain.org/v1alpha1
kind: Asset
metadata:
  labels:
    app.kubernetes.io/name: asset
    app.kubernetes.io/instance: asset-sample
    app.kubernetes.io/part-of: teranode-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: teranode-operator
  name: asset-sample
spec:
  # TODO(user): Add fields here
  resources:
    requests:
      cpu: 1
      memory: 1Gi
    limits:
      memory: 2Gi
  image: localhost/ubsv:latest
  imagePullPolicy: Never
