apiVersion: teranode.bsvblockchain.org/v1alpha1
kind: Asset
metadata:
  labels:
    app.kubernetes.io/created-by: teranode-operator
    app.kubernetes.io/instance: asset-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: asset
    app.kubernetes.io/part-of: teranode-operator
  name: asset-sample
spec:
  imagePullPolicy: Always
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 1
      memory: 1Gi
