apiVersion: teranode.bsvblockchain.org/v1alpha1
kind: Validator
metadata:
  labels:
    app.kubernetes.io/name: validator
    app.kubernetes.io/instance: validator-sample
    app.kubernetes.io/part-of: teranode-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: teranode-operator
  name: validator-sample
spec:
  resources:
    requests:
      cpu: 1
      memory: 1Gi
    limits:
      memory: 2Gi
  image: 434394763103.dkr.ecr.eu-north-1.amazonaws.com/ubsv:v2.2.6
  imagePullPolicy: Always