apiVersion: teranode.bsvblockchain.org/v1alpha1
kind: TransactionBlaster
metadata:
  labels:
    app.kubernetes.io/name: transactionblaster
    app.kubernetes.io/instance: transactionblaster-sample
    app.kubernetes.io/part-of: teranode-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: teranode-operator
  name: transactionblaster-sample
spec:
  # TODO(user): Add fields here
