# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/teranode.bsvblockchain.org_nodes.yaml
- bases/teranode.bsvblockchain.org_assets.yaml
- bases/teranode.bsvblockchain.org_blockchains.yaml
- bases/teranode.bsvblockchain.org_peers.yaml
- bases/teranode.bsvblockchain.org_subtreevalidators.yaml
- bases/teranode.bsvblockchain.org_faucets.yaml
- bases/teranode.bsvblockchain.org_propagations.yaml
- bases/teranode.bsvblockchain.org_blockpersisters.yaml
- bases/teranode.bsvblockchain.org_miners.yaml
- bases/teranode.bsvblockchain.org_validators.yaml
- bases/teranode.bsvblockchain.org_coinbases.yaml
- bases/teranode.bsvblockchain.org_bootstraps.yaml
- bases/teranode.bsvblockchain.org_blockassemblies.yaml
- bases/teranode.bsvblockchain.org_blockvalidators.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- path: patches/webhook_in_nodes.yaml
#- path: patches/webhook_in_assets.yaml
#- path: patches/webhook_in_blockchains.yaml
#- path: patches/webhook_in_peers.yaml
#- path: patches/webhook_in_subtreevalidators.yaml
#- path: patches/webhook_in_faucets.yaml
#- path: patches/webhook_in_propagations.yaml
#- path: patches/webhook_in_blockpersisters.yaml
#- path: patches/webhook_in_miners.yaml
#- path: patches/webhook_in_validators.yaml
#- path: patches/webhook_in_coinbases.yaml
#- path: patches/webhook_in_bootstraps.yaml
#- path: patches/webhook_in_blockassemblies.yaml
#- path: patches/webhook_in_blockvalidators.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- path: patches/cainjection_in_nodes.yaml
#- path: patches/cainjection_in_assets.yaml
#- path: patches/cainjection_in_blockchains.yaml
#- path: patches/cainjection_in_peers.yaml
#- path: patches/cainjection_in_subtreevalidators.yaml
#- path: patches/cainjection_in_faucets.yaml
#- path: patches/cainjection_in_propagations.yaml
#- path: patches/cainjection_in_blockpersisters.yaml
#- path: patches/cainjection_in_miners.yaml
#- path: patches/cainjection_in_validators.yaml
#- path: patches/cainjection_in_coinbases.yaml
#- path: patches/cainjection_in_bootstraps.yaml
#- path: patches/cainjection_in_blockassemblies.yaml
#- path: patches/cainjection_in_blockvalidators.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# [WEBHOOK] To enable webhook, uncomment the following section
# the following config is for teaching kustomize how to do kustomization for CRDs.

#configurations:
#- kustomizeconfig.yaml
